language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "4.1"
  - "4.2"
  - "4.3"
  - "4.4"
  - "4.5"
  - "6.0"
  - "6.1"
  - "6.2"
  - "6.3"
  - "6.4"
  - "6.5"
  - "6.6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
